#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
	yay="paru" \
alias yt-low="pipe-viewer --resolution="360p""
alias yt-normal="pipe-viewer --resolution="1080p""
#alias view="nomacs"
alias view="sxiv"
alias pdf="zathura"
alias yubi="yubioath-desktop"
alias la="ls -a"
alias ll="ls -l"
alias lla="ls -a -l"
alias clip="xclip -selection clipboard"
alias imgclip="xclip -selection clipboard -t image/png -i 1g6dg969txg51.png"
alias cs='cdls'
alias nd280-setup=". /home/till/nd280software/nd280SoftwarePilot/nd280SoftwarePilot.profile"
alias chess='scid'
alias mutt='neomutt'
alias csv='sc-im'
alias sl='ls'
alias mykb='nvim ~/Documents/vimwiki/mykb/index.md'
alias vmmt='nvim ~/Documents/vimwiki/MT/index.md'
alias vm='nvim ~/Documents/vimwiki/General/index.md'


# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="sudo shutdown -h now" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" \
	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" \
alias config='/usr/bin/git --git-dir=/home/till/.cfg/ --work-tree=/home/till'
alias config='/usr/bin/git --git-dir=/home/till/.cfg/ --work-tree=/home/till'
alias config='/usr/bin/git --git-dir=/home/till/.cfg/ --work-tree=/home/till'
