#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# This file's true location is in ~/.config/xprofile and a link exists to it in
# ~/.xprofile. If you do not use a DM, you may remove the link to it to have a
# cleaner home.

# Fix Gnome Apps Slow  Start due to failing services
# Add this when you include flatpak in your system
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

mpd &			# music player daemon-you might prefer it as a service though
remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/Xresources &	# Uncomment to use Xresources colors/settings on startup
xcompmgr &		# xcompmgr for transparency
#owncloud &		# Start owncloud for Polybox
dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up (speed of keypresses)
unclutter &		# Remove mouse when idle
calcurse --daemon &
protonmail-bridge --no-window &     #start mailbridge
touchpad &              # Deactivate touchpad
#ckb-next --background & # Start tastatur beleuchtung
export LC_ALL=en_US.UTF-8 #Int Layout
export USE_WOLFRAM_LD_LIBRARY_PATH=1
export WEECHAT_HOME='/home/till/.config/weechat'
sleep 2
#vpn NL &
update_musicbar &  #Update Music in dmw instantly when changed
#sleep 10
#update &
alias config='/usr/bin/git --git-dir=/home/till/.cfg/ --work-tree=/home/till'
